# -*- coding: utf-8 -*-
"""xAI_LIME.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13q6QJPsPtc67xAR6W8n_yADPbzTikKDB
"""

import os
import numpy as np
import pandas as pd
from lime.lime_text import LimeTextExplainer
from transformers import pipeline
from sklearn.model_selection import train_test_split

# Load the dataset dynamically
file_path = "./dataset/fake_reviews_dataset.csv"
data = pd.read_csv(file_path)

# Ensure necessary columns are present and clean the dataset
data = data[['label', 'text']].fillna('')

# Split into training, validation, and test sets
train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    data['text'], data['label'], test_size=0.3, random_state=42
)
val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts, temp_labels, test_size=0.5, random_state=42
)

# Load TinyLlama tokenizer and model
model_name = "./models/TinyLlama/TinyLlama_v1.1"  # Replace with the actual model identifier
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

# Define the class names
class_names = ["AI Generated", "Human Written"]

# Wrap the model and tokenizer in a prediction function for LIME
explainable_pipeline = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0)

def prediction_function(texts):
    preds = explainable_pipeline(texts)
    # Convert predictions into the format LIME expects
    return np.array([[1 - p["score"], p["score"]] for p in preds])

# Create LIME Explainer
explainer = LimeTextExplainer(class_names=class_names)

# Select indices for True Positive (TP), True Negative (TN), False Positive (FP), and False Negative (FN)
predictions = explainable_pipeline(test_texts.tolist())
predicted_labels = [1 if p['label'] == 'LABEL_1' else 0 for p in predictions]

tp_indices = [i for i, (true, pred) in enumerate(zip(test_labels, predicted_labels)) if true == 1 and pred == 1]
tn_indices = [i for i, (true, pred) in enumerate(zip(test_labels, predicted_labels)) if true == 0 and pred == 0]
fp_indices = [i for i, (true, pred) in enumerate(zip(test_labels, predicted_labels)) if true == 0 and pred == 1]
fn_indices = [i for i, (true, pred) in enumerate(zip(test_labels, predicted_labels)) if true == 1 and pred == 0]

# Select one example from each category
examples = {
    "True Positive (TP)": test_texts.iloc[tp_indices[0]] if tp_indices else None,
    "True Negative (TN)": test_texts.iloc[tn_indices[0]] if tn_indices else None,
    "False Positive (FP)": test_texts.iloc[fp_indices[0]] if fp_indices else None,
    "False Negative (FN)": test_texts.iloc[fn_indices[0]] if fn_indices else None,
}

# Explain and Summarize Results for One Example Per Category
for category, text in examples.items():
    if text is None:
        print(f"No examples available for {category}.")
        continue

    print(f"\nExplaining {category}:")
    print(f"Text: {text}")

    # Generate explanation
    explanation = explainer.explain_instance(
        text,
        prediction_function,
        num_features=10
    )

    # Save explanation as HTML file
    explanation.save_to_file(f"{category.replace(' ', '_')}_explanation.html")

    # Print key features and contributions
    print("\nKey Features and Contributions:")
    for feature, weight in explanation.as_list():
        print(f"Feature: {feature}, Contribution: {weight}")

# Filter and print examples for each label
label_0_examples = data[data['label'] == 0]['text'].tolist()
label_1_examples = data[data['label'] == 1]['text'].tolist()

print("\nExamples with Label = 0 (AI Generated):")
for i, text in enumerate(label_0_examples[:5]):
    print(f"{i+1}. {text}")

print("\nExamples with Label = 1 (Human Written):")
for i, text in enumerate(label_1_examples[:5]):
    print(f"{i+1}. {text}")